merge primary

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: build
+name: CI
 
 on:
   push:
@@ -6,8 +6,12 @@ on:
   pull_request:
     branches: ["primary"]
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
-  build:
+  run-lutecli-luau-tests:
     runs-on: ${{ matrix.os }}
 
     strategy:
@@ -16,16 +20,18 @@ jobs:
           - os: windows-latest
             options: --c-compiler cl.exe --cxx-compiler cl.exe
           - os: ubuntu-latest
-            options: --c-compiler gcc --cxx-compiler g++
+            options: --c-compiler gcc --cxx-compiler g++ --enable-asan
           - os: ubuntu-latest
-            options: --c-compiler clang --cxx-compiler clang++
+            options: --c-compiler clang --cxx-compiler clang++ --enable-asan
           - os: macos-latest
+            options: --enable-asan
       fail-fast: false
 
     steps:
       - uses: actions/checkout@v4
 
       - name: Setup and Build Lute
+        id: build_lute
         uses: ./.github/actions/setup-and-build
         with:
           target: Lute.CLI
@@ -33,7 +39,13 @@ jobs:
           options: ${{ matrix.options }}
           token: ${{ secrets.GITHUB_TOKEN }}
 
-  test:
+      - name: Remove .luaurc file
+        run: rm .luaurc
+
+      - name: Run Luau Tests
+        run: find tests -name "*.test.luau" | xargs -I {} ${{ steps.build_lute.outputs.exe_path }} run {}
+
+  run-lute-cxx-unittests:
     runs-on: ${{ matrix.os }}
 
     strategy:
@@ -42,17 +54,18 @@ jobs:
           - os: windows-latest
             options: --c-compiler cl.exe --cxx-compiler cl.exe
           - os: ubuntu-latest
-            options: --c-compiler gcc --cxx-compiler g++
+            options: --c-compiler gcc --cxx-compiler g++ --enable-asan
           - os: ubuntu-latest
-            options: --c-compiler clang --cxx-compiler clang++
+            options: --c-compiler clang --cxx-compiler clang++ --enable-asan
           - os: macos-latest
+            options: --enable-asan
       fail-fast: false
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Setup and Build Tests
+      - name: Setup and Build C++ Unit Tests
         id: build_tests
         uses: ./.github/actions/setup-and-build
         with:
@@ -60,11 +73,10 @@ jobs:
           config: debug
           options: ${{ matrix.options }}
           token: ${{ secrets.GITHUB_TOKEN }}
-
       - name: Remove .luaurc file
         run: rm .luaurc
 
-      - name: Run Tests
+      - name: Run C++ Tests
         run: ${{ steps.build_tests.outputs.exe_path }}
 
   check-format:
@@ -82,13 +94,47 @@ jobs:
       - name: Run StyLua
         run: stylua --check .
 
+  build-docs-site:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+
+      - name: Install tools
+        uses: Roblox/setup-foreman@v3
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          allow-external-github-orgs: true
+
+      - name: Install dependencies
+        run: npm install
+        working-directory: docs
+
+      - name: Build docs site
+        run: npm run build
+        working-directory: docs
+
+      - name: Upload docs artifact
+        id: deployment
+        uses: actions/upload-pages-artifact@v3
+        with:
+          path: docs/.vitepress/dist/
+
   aggregator:
     name: Gated Commits
     runs-on: ubuntu-latest
-    needs:
-      - build
+    needs: [run-lutecli-luau-tests, run-lute-cxx-unittests, check-format]
     if: ${{ always() }}
     steps:
-      - name: Aggregate
+      - name: Aggregator
         run: |
-          echo "All required jobs completed"
+          if [ "${{ needs.run-lutecli-luau-tests.result }}" == "success" ] && [ "${{ needs.run-lute-cxx-unittests.result }}" == "success" ] && [ "${{ needs.check-format.result }}" == "success" ]; then
+            echo "All jobs succeeded"
+          else
+            echo "One or more jobs failed"
+            exit 1
+          fi
